//1._DEJAR SOLO DENTRO DEL SRC app.module y eliminar lo demas (tambien importaciones) TAMBIEN BORRAR LA REFERENCIA A CONTROLADORES EN APP.MODULE
//2._nest g res pokemon --no-spec
//3._CREAR EL ARCHIVO DOCKER COMPOSE.YAML
//4._docker-compose up -d
//5._En docker se crea un contenedor e imagen
//6._TABLE PLUS nueva conexxion mongo dg crear y ponemos solo la url que es mongobd://localhost:27017/el nombre que le pusiste en tu docker compose MONGODB_DATABASE
//7._Concetar mongoose con nest yarn add @nestjs/mongoose mongoose
//8._EN APP.MODULE PONER EL MongooseModule.forRoot Y ADENTRO LA URL que antes pusimos en table
//9._TRABAJAR EN POKEMON ENTITY es para añadir colecciones y documentos en bd
//10._IR A POKEMON MODULE E IMPORTAR
//11._EMPEZAMOS CON LAS VALIDACIONES EN CREATEPOKEMON INSTALAMAOS yarn add class-validator class-transformer y en main ts poner de manera global el app.useGlobalPipes
//12._VALIDACIONES EN EL DTO CON DECORADORES DEPENDE DE LO QUE QUIERAS EVALUAR
//13._INSETAR EN BD, CONSTRUCTOR SOLO ES PARA INYECCION DE DEPENDENCIAS EN SERVICE CONSTRUCTOR
//14._CREAR METODOS EN SERVICIO Y CONTROLADOR
//15._PIPE CREAR nest g mo common Y nest g pi common/pipes/parseMongoId --no-spec Y ya dependiendo de lo que necesites...
//16._INYECCION DE SEED... inyectar el constructor con el modelo de pokemon
//17._EN POKEMON MODULO EXPORTAMOS EL MONGOOSE MODULE
//18._IMPORTAMOS EL POKEMON MODULE EN SEED MODULE
//19._COPIAMOS LA LINEA DE CREATE DE POKEMON SERVICE Y LA PEGAMOS EN SEED SERVICE
//VARIABLES DE ENTORNO CREAMOS EL ARCHIVO DE VARIABLES Y EN APP.MODULE LE AGREGAMOS ESO Y CAMBIAMOS POR LA VARIABLE
//CREAMOS NUEVA CARPETA Y DENTRO UN ARCHIVO CON LAS VARIBALES DE ENTORNO Y ESTE LO PEGAMOS EN APP.MODULE E ROOT
//PARA ACCEDER HACEMOS this.defaultLimit = configService.get<number>('defaultLimit')!;
//AGREGAR JOI PARA PODER DAR ERRORES YARN ADD JOI
//AHORA VAMOS A CONECTAR ÑA BD EN LA NUBE, YA NO DE MANERA LOCAL, PRIMERO NOS VAMOS A MONGO ATLAS, INICIAMOS SESION Y CREAMOS UN CLUSTER GRAAATIS
//EN SEGURIDAD NOS CREAMOS UN UN NUEVO USUARIO Y CONTRASEÑA, NOS REGRESAMOS A CLUSTER Y CONECTAR CON MONGO COMPASS ABRIMOS COMPASS Y COPIMOS LA URL Y LA PEGAMOS EN NUESVA CONEXION
//PEGANDO EL USUARIO Y CONTRASEÑA
//LUEGO EN EL CODIGO CAMBIAMOS ESA URL POR MONGODB EN EL .ENV Y EN EL APP MODULE AGREGAMOS {dbName: 'pokemondb',} EN FOR ROOT
//BAJAMOS EL SERVICIO Y LO SUBIMOS DE NUEVO
